default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  host: localhost
  password: maia2015
  port: 5432


development:
  <<: *default
  database: project_form_development

test:
  <<: *default
  database: project_form_test

production:
  <<: *default
  database: project_form_production
  username: 
  password:
  #username: BlogApp
  #password: <%= ENV["BLOGAPP_DATABASE_PASSWORD"] %> 
